"""
State-value model for CxT — Phase 7b.

Target: possession_cxg — the total (discounted) CxG generated by the
        possessing team from all shots in the same possession.

Discount factor 0.9 per shot index (shots later in the possession are
downweighted) to reward actions that more directly precede goal threat.

        possession_cxg = Σ_{k} 0.9^k * cxg_k
        where k = shot index within the possession (0-indexed)

This is a regression on a non-negative target. Possessions that do not
generate a shot have target = 0.

Model ladder (all regressors):
  1. gamma_glm          — Gamma GLM (log link); requires target > 0
  2. xgb_contextual     — XGBoost regressor
  3. lgbm_contextual    — LightGBM regressor
  4. ffnn_contextual    — Feed-forward neural network with Huber loss

Evaluation: MAE, RMSE, Spearman rank correlation, calibration by zone bucket.
"""

from __future__ import annotations

import logging
import pickle
from dataclasses import dataclass, field
from pathlib import Path
from typing import Callable

import numpy as np
import pandas as pd
from scipy.stats import spearmanr
from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.linear_model import TweedieRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OrdinalEncoder, StandardScaler

from src.evaluation.validation_splits import match_kfold
from src.models.cxt.feature_sets import CxTFeatureSetSpec, get_feature_set

logger = logging.getLogger(__name__)

# Discount factor for shots later in the same possession
SHOT_DISCOUNT = 0.9


# ── Metrics ───────────────────────────────────────────────────────────────────

@dataclass
class StateValueMetrics:
    mae: float
    rmse: float
    spearman: float | None
    calibration_by_zone: dict[str, float] = field(default_factory=dict)


@dataclass
class StateValueLadderResult:
    name: str
    family: str
    feature_set: str
    cv_mae: float
    cv_rmse: float
    cv_spearman: float | None
    n_cv_folds_used: int
    model: object = field(repr=False)
    rank: int = 0


# ── Shared helpers ────────────────────────────────────────────────────────────

def compute_possession_cxg(
    actions_df: pd.DataFrame,
    cxg_col: str = "event_cxg",
    possession_id_col: str = "possession_id",
    match_id_col: str = "match_id",
    discount: float = SHOT_DISCOUNT,
) -> pd.Series:
    """
    Compute discounted possession CxG for every action row.

    For each action, possession_cxg = Σ 0.9^k * cxg_k for all shots in
    the same possession (match_id + possession_id), regardless of when
    in the possession the action occurs.

    Returns a Series indexed the same as actions_df.
    """
    group_cols = [c for c in [match_id_col, possession_id_col] if c in actions_df.columns]
    if not group_cols or cxg_col not in actions_df.columns:
        return pd.Series(0.0, index=actions_df.index)

    # Compute discounted possession CxG per (match_id, possession_id)
    poss_cxg: dict = {}
    for key, grp in actions_df.groupby(group_cols):
        shots = grp[grp[cxg_col] > 0][cxg_col].to_numpy()
        if len(shots) == 0:
            val = 0.0
        else:
            val = float(sum(discount**k * cxg for k, cxg in enumerate(shots)))
        poss_cxg[key if len(group_cols) > 1 else key[0]] = val

    def _lookup(row):
        key = tuple(row[c] for c in group_cols) if len(group_cols) > 1 else row[group_cols[0]]
        return poss_cxg.get(key, 0.0)

    return actions_df[group_cols].apply(_lookup, axis=1)


def _make_X(
    df: pd.DataFrame,
    numeric_all: list[str],
    cat_cols: list[str],
    bool_set: frozenset[str],
) -> pd.DataFrame:
    """Build feature matrix from before-state columns."""
    cols = [c for c in numeric_all + cat_cols if c in df.columns]
    X = df[cols].copy()
    for c in bool_set:
        if c in X.columns:
            X[c] = X[c].astype(float)
    return X


def _build_gamma_pipeline(numeric_all: list[str], cat_cols: list[str], alpha: float = 1.0) -> Pipeline:
    from sklearn.preprocessing import OneHotEncoder
    transformers: list = [("num", Pipeline([
        ("imp", SimpleImputer(strategy="median")),
        ("sc", StandardScaler()),
    ]), numeric_all)]
    if cat_cols:
        transformers.append(("cat", Pipeline([
            ("imp", SimpleImputer(strategy="constant", fill_value="unknown")),
            ("ohe", OneHotEncoder(handle_unknown="ignore", sparse_output=False)),
        ]), cat_cols))
    pre = ColumnTransformer(transformers, remainder="drop")
    return Pipeline([("pre", pre), ("reg", TweedieRegressor(power=2, alpha=alpha, max_iter=2000, link="log"))])


def _build_tweedie_pipeline(numeric_all: list[str], cat_cols: list[str], power: float = 1.5, alpha: float = 1.0) -> Pipeline:
    """Tweedie GLM pipeline. power=1.5 handles zero-inflated non-negative targets natively."""
    from sklearn.preprocessing import OneHotEncoder
    transformers: list = [("num", Pipeline([
        ("imp", SimpleImputer(strategy="median")),
        ("sc", StandardScaler()),
    ]), numeric_all)]
    if cat_cols:
        transformers.append(("cat", Pipeline([
            ("imp", SimpleImputer(strategy="constant", fill_value="unknown")),
            ("ohe", OneHotEncoder(handle_unknown="ignore", sparse_output=False)),
        ]), cat_cols))
    pre = ColumnTransformer(transformers, remainder="drop")
    return Pipeline([("pre", pre), ("reg", TweedieRegressor(power=power, alpha=alpha, max_iter=2000, link="log"))])


def _build_tree_reg_pipeline(estimator, numeric_all: list[str], cat_cols: list[str]) -> Pipeline:
    transformers: list = [("num", SimpleImputer(strategy="median"), numeric_all)]
    if cat_cols:
        transformers.append(("cat", Pipeline([
            ("imp", SimpleImputer(strategy="constant", fill_value="unknown")),
            ("enc", OrdinalEncoder(handle_unknown="use_encoded_value", unknown_value=-1, dtype=float)),
        ]), cat_cols))
    pre = ColumnTransformer(transformers, remainder="drop")
    return Pipeline([("pre", pre), ("reg", estimator)])


def _evaluate_regression(y_true: np.ndarray, y_pred: np.ndarray) -> StateValueMetrics:
    mae = float(mean_absolute_error(y_true, y_pred))
    rmse = float(np.sqrt(mean_squared_error(y_true, y_pred)))
    corr, _ = spearmanr(y_true, y_pred)
    spearman = float(corr) if not np.isnan(corr) else None
    # Calibration by zone (quartiles on positive targets only)
    buckets: dict[str, float] = {}
    try:
        pos_mask = y_true > 0
        if pos_mask.sum() >= 4:
            q = np.quantile(y_true[pos_mask], [0.25, 0.5, 0.75])
            edges = [0.0] + q.tolist() + [float("inf")]
            for i in range(len(edges) - 1):
                mask = (y_true >= edges[i]) & (y_true < edges[i + 1])
                if mask.sum() > 0:
                    buckets[f"q{i+1}"] = float(np.mean(y_pred[mask]) - np.mean(y_true[mask]))
    except Exception:
        pass
    return StateValueMetrics(mae=mae, rmse=rmse, spearman=spearman, calibration_by_zone=buckets)


# ── Base class ────────────────────────────────────────────────────────────────

class _BaseStateValueModel:
    feature_set: CxTFeatureSetSpec
    _numeric_all: list[str]
    _cat_cols: list[str]
    _bool_set: frozenset[str]
    pipeline: Pipeline | None

    def _resolve_cols(self, df: pd.DataFrame) -> tuple[list[str], list[str]]:
        numeric_all = [c for c in self.feature_set.numeric_all if c in df.columns]
        cat_cols = [c for c in self.feature_set.categorical if c in df.columns]
        return numeric_all, cat_cols

    def _X(self, df: pd.DataFrame) -> pd.DataFrame:
        return _make_X(df, self._numeric_all, self._cat_cols, self._bool_set)

    def predict(self, actions_df: pd.DataFrame) -> np.ndarray:
        if self.pipeline is None:
            raise RuntimeError("Model not fitted. Call fit() first.")
        return np.clip(self.pipeline.predict(self._X(actions_df)), 0.0, None)

    def evaluate(self, actions_df: pd.DataFrame, target_col: str = "possession_cxg") -> StateValueMetrics:
        y = actions_df[target_col].astype(float).to_numpy()
        p = self.predict(actions_df)
        return _evaluate_regression(y, p)

    def save(self, path: str | Path) -> None:
        Path(path).parent.mkdir(parents=True, exist_ok=True)
        with open(path, "wb") as f:
            pickle.dump(self, f)

    @classmethod
    def load(cls, path: str | Path):
        with open(path, "rb") as f:
            return pickle.load(f)


# ── Gamma GLM (positive targets only) ────────────────────────────────────────

class GammaStateValueModel(_BaseStateValueModel):
    """Gamma GLM state-value model. Requires strictly positive target values."""

    def __init__(
        self,
        feature_set: str | CxTFeatureSetSpec = "contextual",
        alpha: float = 1.0,
        random_state: int = 42,
    ) -> None:
        self.feature_set = get_feature_set(feature_set) if isinstance(feature_set, str) else feature_set
        self.alpha = alpha
        self.random_state = random_state
        self.pipeline: Pipeline | None = None
        self._numeric_all: list[str] = []
        self._cat_cols: list[str] = []
        self._bool_set: frozenset[str] = frozenset()

    def fit(self, actions_df: pd.DataFrame, target_col: str = "possession_cxg") -> "GammaStateValueModel":
        if actions_df.empty:
            raise ValueError("actions_df is empty")
        if target_col not in actions_df.columns:
            raise ValueError(f"Missing target column: {target_col!r}")
        y = actions_df[target_col].astype(float)
        if (y <= 0).any():
            raise ValueError(
                "GammaStateValueModel requires strictly positive targets. "
                "Filter rows with possession_cxg <= 0 before fitting."
            )
        numeric_all, cat_cols = self._resolve_cols(actions_df)
        if not numeric_all:
            raise ValueError("No numeric feature columns found")
        self._numeric_all = numeric_all
        self._cat_cols = cat_cols
        self._bool_set = frozenset(c for c in self.feature_set.boolean if c in numeric_all)
        self.pipeline = _build_gamma_pipeline(numeric_all, cat_cols, self.alpha)
        self.pipeline.fit(self._X(actions_df), y.to_numpy())
        return self


# ── Tweedie GLM (zero-inflated non-negative) ──────────────────────────────────

class TweedieStateValueModel(_BaseStateValueModel):
    """
    Tweedie GLM state-value model (log link, default power=1.5).

    Tweedie with 1 < power < 2 places a point mass at zero and models the
    positive tail with a Gamma-like distribution — suited for the 84%-zero
    possession_cxg target without discarding zero rows (unlike GammaStateValueModel).
    """

    def __init__(
        self,
        feature_set: str | CxTFeatureSetSpec = "contextual",
        power: float = 1.5,
        alpha: float = 1.0,
        random_state: int = 42,
    ) -> None:
        self.feature_set = get_feature_set(feature_set) if isinstance(feature_set, str) else feature_set
        self.power = power
        self.alpha = alpha
        self.random_state = random_state
        self.pipeline: Pipeline | None = None
        self._numeric_all: list[str] = []
        self._cat_cols: list[str] = []
        self._bool_set: frozenset[str] = frozenset()

    def fit(self, actions_df: pd.DataFrame, target_col: str = "possession_cxg") -> "TweedieStateValueModel":
        if actions_df.empty:
            raise ValueError("actions_df is empty")
        if target_col not in actions_df.columns:
            raise ValueError(f"Missing target column: {target_col!r}")
        y = actions_df[target_col].astype(float)
        if (y < 0).any():
            raise ValueError("TweedieStateValueModel requires non-negative targets (y >= 0).")
        numeric_all, cat_cols = self._resolve_cols(actions_df)
        if not numeric_all:
            raise ValueError("No numeric feature columns found")
        self._numeric_all = numeric_all
        self._cat_cols = cat_cols
        self._bool_set = frozenset(c for c in self.feature_set.boolean if c in numeric_all)
        self.pipeline = _build_tweedie_pipeline(numeric_all, cat_cols, self.power, self.alpha)
        self.pipeline.fit(self._X(actions_df), y.to_numpy())
        return self


# ── GAM (splines over spatial features, GammaGAM family) ─────────────────────

class GAMStateValueModel(_BaseStateValueModel):
    """
    GAM state-value model using pygam with mixed spline/linear terms.

    Spline terms (s()) applied to known continuous spatial features;
    linear terms (l()) for binary/other numeric features.
    Trained on strictly positive targets (GammaGAM family requirement).

    Requires: pip install pygam
    """

    _SPLINE_FEATURES: frozenset[str] = frozenset({
        "x_location", "y_location", "distance_to_goal",
        "end_x", "end_y", "end_distance_to_goal",
        "sequence_length", "minute", "keeper_distance_to_goal",
        "shot_angle",
    })

    def __init__(
        self,
        feature_set: str | CxTFeatureSetSpec = "contextual",
        n_splines: int = 20,
        lam: float = 0.6,
        random_state: int = 42,
    ) -> None:
        try:
            import pygam  # noqa: F401
        except ImportError as exc:
            raise ImportError("pygam not installed. Run: pip install pygam") from exc
        self.feature_set = get_feature_set(feature_set) if isinstance(feature_set, str) else feature_set
        self.n_splines = n_splines
        self.lam = lam
        self.random_state = random_state
        self.pipeline: Pipeline | None = None  # unused; preprocessing handled manually
        self._gam = None
        self._imputer: SimpleImputer | None = None
        self._scaler: StandardScaler | None = None
        self._numeric_all: list[str] = []
        self._cat_cols: list[str] = []
        self._bool_set: frozenset[str] = frozenset()
        self._feature_names: list[str] = []

    def _build_terms(self, feature_names: list[str]):
        from pygam import s, l  # noqa: E741
        terms = None
        for i, name in enumerate(feature_names):
            t = s(i, n_splines=self.n_splines) if name in self._SPLINE_FEATURES else l(i)
            terms = t if terms is None else terms + t
        return terms

    def _preprocess_X(self, df: pd.DataFrame, fit: bool = False) -> np.ndarray:
        X_df = _make_X(df, self._numeric_all, [], self._bool_set).reindex(
            columns=self._feature_names, fill_value=np.nan
        )
        if fit:
            self._imputer = SimpleImputer(strategy="median")
            self._scaler = StandardScaler()
            X_np = self._imputer.fit_transform(X_df)
            return self._scaler.fit_transform(X_np).astype(float)
        return self._scaler.transform(
            self._imputer.transform(X_df)
        ).astype(float)

    def fit(self, actions_df: pd.DataFrame, target_col: str = "possession_cxg") -> "GAMStateValueModel":
        from pygam import GammaGAM
        if actions_df.empty:
            raise ValueError("actions_df is empty")
        if target_col not in actions_df.columns:
            raise ValueError(f"Missing target column: {target_col!r}")
        y = actions_df[target_col].astype(float)
        if (y <= 0).any():
            raise ValueError(
                "GAMStateValueModel (GammaGAM) requires strictly positive targets. "
                "Filter rows with possession_cxg <= 0 before fitting."
            )
        numeric_all, cat_cols = self._resolve_cols(actions_df)
        if not numeric_all:
            raise ValueError("No numeric feature columns found")
        self._numeric_all = numeric_all
        self._cat_cols = cat_cols
        self._bool_set = frozenset(c for c in self.feature_set.boolean if c in numeric_all)
        self._feature_names = numeric_all  # GAM uses numeric features only
        X = self._preprocess_X(actions_df, fit=True)
        terms = self._build_terms(self._feature_names)
        self._gam = GammaGAM(terms, lam=self.lam).fit(X, y.to_numpy())
        return self

    def predict(self, actions_df: pd.DataFrame) -> np.ndarray:
        if self._gam is None:
            raise RuntimeError("Model not fitted. Call fit() first.")
        X = self._preprocess_X(actions_df, fit=False)
        return np.clip(self._gam.predict(X), 0.0, None)


# ── XGBoost ───────────────────────────────────────────────────────────────────

class XGBoostStateValueModel(_BaseStateValueModel):
    """XGBoost state-value regressor."""

    def __init__(
        self,
        feature_set: str | CxTFeatureSetSpec = "contextual",
        n_estimators: int = 400,
        learning_rate: float = 0.05,
        max_depth: int = 6,
        subsample: float = 0.8,
        colsample_bytree: float = 0.8,
        min_child_weight: int = 5,
        reg_lambda: float = 1.0,
        random_state: int = 42,
    ) -> None:
        try:
            import xgboost  # noqa: F401
        except ImportError as exc:
            raise ImportError("xgboost not installed. Run: poetry install --with models") from exc
        self.feature_set = get_feature_set(feature_set) if isinstance(feature_set, str) else feature_set
        self.params = dict(
            n_estimators=n_estimators, learning_rate=learning_rate,
            max_depth=max_depth, subsample=subsample,
            colsample_bytree=colsample_bytree, min_child_weight=min_child_weight,
            reg_lambda=reg_lambda,
        )
        self.random_state = random_state
        self.pipeline: Pipeline | None = None
        self._numeric_all: list[str] = []
        self._cat_cols: list[str] = []
        self._bool_set: frozenset[str] = frozenset()

    def fit(self, actions_df: pd.DataFrame, target_col: str = "possession_cxg") -> "XGBoostStateValueModel":
        if actions_df.empty:
            raise ValueError("actions_df is empty")
        if target_col not in actions_df.columns:
            raise ValueError(f"Missing target column: {target_col!r}")
        import xgboost as xgb
        from src.runtime.gbm_device import xgboost_kwargs
        df = actions_df.reset_index(drop=True)
        numeric_all, cat_cols = self._resolve_cols(df)
        if not numeric_all:
            raise ValueError("No feature columns found")
        self._numeric_all = numeric_all
        self._cat_cols = cat_cols
        self._bool_set = frozenset(c for c in self.feature_set.boolean if c in numeric_all)
        est = xgb.XGBRegressor(
            **self.params, **xgboost_kwargs(getattr(self, "device", None)),
            objective="reg:squarederror",
            verbosity=0, random_state=self.random_state,
        )
        self.pipeline = _build_tree_reg_pipeline(est, numeric_all, cat_cols)
        self.pipeline.fit(self._X(df), df[target_col].astype(float).to_numpy())
        return self


# ── LightGBM ──────────────────────────────────────────────────────────────────

class LightGBMStateValueModel(_BaseStateValueModel):
    """LightGBM state-value regressor."""

    def __init__(
        self,
        feature_set: str | CxTFeatureSetSpec = "contextual",
        n_estimators: int = 400,
        learning_rate: float = 0.05,
        num_leaves: int = 63,
        subsample: float = 0.8,
        colsample_bytree: float = 0.8,
        min_child_samples: int = 20,
        random_state: int = 42,
    ) -> None:
        try:
            import lightgbm  # noqa: F401
        except ImportError as exc:
            raise ImportError("lightgbm not installed. Run: poetry install --with models") from exc
        self.feature_set = get_feature_set(feature_set) if isinstance(feature_set, str) else feature_set
        self.params = dict(
            n_estimators=n_estimators, learning_rate=learning_rate,
            num_leaves=num_leaves, subsample=subsample,
            colsample_bytree=colsample_bytree, min_child_samples=min_child_samples,
        )
        self.random_state = random_state
        self.pipeline: Pipeline | None = None
        self._numeric_all: list[str] = []
        self._cat_cols: list[str] = []
        self._bool_set: frozenset[str] = frozenset()

    def fit(self, actions_df: pd.DataFrame, target_col: str = "possession_cxg") -> "LightGBMStateValueModel":
        if actions_df.empty:
            raise ValueError("actions_df is empty")
        if target_col not in actions_df.columns:
            raise ValueError(f"Missing target column: {target_col!r}")
        import lightgbm as lgb
        from src.runtime.gbm_device import lightgbm_kwargs
        df = actions_df.reset_index(drop=True)
        numeric_all, cat_cols = self._resolve_cols(df)
        if not numeric_all:
            raise ValueError("No feature columns found")
        self._numeric_all = numeric_all
        self._cat_cols = cat_cols
        self._bool_set = frozenset(c for c in self.feature_set.boolean if c in numeric_all)
        est = lgb.LGBMRegressor(
            **self.params, **lightgbm_kwargs(getattr(self, "device", None)),
            objective="regression", metric="rmse",
            verbose=-1, random_state=self.random_state,
        )
        self.pipeline = _build_tree_reg_pipeline(est, numeric_all, cat_cols)
        self.pipeline.fit(self._X(df), df[target_col].astype(float).to_numpy())
        return self


# ── FFNN ──────────────────────────────────────────────────────────────────────

class FFNNStateValueModel(_BaseStateValueModel):
    """
    Feed-forward neural network state-value model with Huber loss.

    Architecture: Linear(d_in → 256) → ReLU → Dropout(0.1) →
                  Linear(256 → 128) → ReLU → Dropout(0.1) → Linear(128 → 1) → Softplus
    """

    def __init__(
        self,
        feature_set: str | CxTFeatureSetSpec = "contextual",
        hidden_dims: tuple[int, ...] = (256, 128),
        lr: float = 1e-3,
        max_epochs: int = 50,
        batch_size: int = 256,
        huber_delta: float = 0.1,
        random_state: int = 42,
    ) -> None:
        self.feature_set = get_feature_set(feature_set) if isinstance(feature_set, str) else feature_set
        self.hidden_dims = hidden_dims
        self.lr = lr
        self.max_epochs = max_epochs
        self.batch_size = batch_size
        self.huber_delta = huber_delta
        self.random_state = random_state
        self.pipeline: Pipeline | None = None  # scaler
        self._torch_model = None
        self._numeric_all: list[str] = []
        self._cat_cols: list[str] = []
        self._bool_set: frozenset[str] = frozenset()

    def _build_torch_model(self, in_dim: int):
        try:
            import torch.nn as nn
        except ImportError as exc:
            raise ImportError("PyTorch not installed.") from exc

        layers: list = []
        prev = in_dim
        for h in self.hidden_dims:
            layers += [nn.Linear(prev, h), nn.ReLU(), nn.Dropout(0.1)]
            prev = h
        layers += [nn.Linear(prev, 1), nn.Softplus()]

        class _MLP(nn.Module):
            def __init__(self, layers):
                super().__init__()
                self.net = nn.Sequential(*layers)
            def forward(self, x):
                return self.net(x).squeeze(-1)

        return _MLP(layers)

    def fit(self, actions_df: pd.DataFrame, target_col: str = "possession_cxg") -> "FFNNStateValueModel":
        try:
            import torch
            import torch.nn as nn
            from torch.utils.data import DataLoader, TensorDataset
        except ImportError as exc:
            raise ImportError("PyTorch not installed. Run: pip install torch") from exc

        if actions_df.empty:
            raise ValueError("actions_df is empty")
        if target_col not in actions_df.columns:
            raise ValueError(f"Missing target column: {target_col!r}")

        torch.manual_seed(self.random_state)
        df = actions_df.reset_index(drop=True)
        numeric_all, _ = self._resolve_cols(df)
        if not numeric_all:
            raise ValueError("No feature columns found")
        self._numeric_all = numeric_all
        self._cat_cols = []  # FFNN uses numeric only
        self._bool_set = frozenset(c for c in self.feature_set.boolean if c in numeric_all)

        from sklearn.pipeline import Pipeline as SKPipeline
        self.pipeline = SKPipeline([
            ("imp", SimpleImputer(strategy="median")),
            ("sc", StandardScaler()),
        ])
        X_raw = _make_X(df, self._numeric_all, [], self._bool_set)[self._numeric_all]
        X_np = self.pipeline.fit_transform(X_raw).astype(np.float32)
        y_np = df[target_col].astype(float).to_numpy(dtype=np.float32)

        dataset = TensorDataset(torch.tensor(X_np), torch.tensor(y_np))
        loader = DataLoader(dataset, batch_size=self.batch_size, shuffle=True)
        model = self._build_torch_model(X_np.shape[1])
        optimizer = torch.optim.AdamW(model.parameters(), lr=self.lr, weight_decay=1e-4)
        criterion = nn.HuberLoss(delta=self.huber_delta)
        model.train()

        for epoch in range(self.max_epochs):
            epoch_loss = 0.0
            for X_batch, y_batch in loader:
                optimizer.zero_grad()
                pred = model(X_batch)
                loss = criterion(pred, y_batch)
                loss.backward()
                torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
                optimizer.step()
                epoch_loss += loss.item()
            if (epoch + 1) % 10 == 0:
                logger.info("FFNNStateValue epoch %d/%d loss=%.4f",
                            epoch + 1, self.max_epochs, epoch_loss / max(len(loader), 1))

        model.eval()
        self._torch_model = model
        return self

    def predict(self, actions_df: pd.DataFrame) -> np.ndarray:
        try:
            import torch
        except ImportError as exc:
            raise ImportError("PyTorch not installed") from exc
        if self._torch_model is None:
            raise RuntimeError("Model not fitted. Call fit() first.")
        df = actions_df.reset_index(drop=True)
        X_raw = _make_X(df, self._numeric_all, [], self._bool_set)[self._numeric_all]
        X_np = self.pipeline.transform(X_raw).astype(np.float32)
        self._torch_model.eval()
        with torch.no_grad():
            out = self._torch_model(torch.tensor(X_np)).numpy()
        return np.clip(out, 0.0, None)


# ── State-Value Ladder ────────────────────────────────────────────────────────

def _cv_state_value(
    factory: Callable[[], _BaseStateValueModel],
    actions_df: pd.DataFrame,
    target_col: str,
    match_id_col: str,
    n_folds: int,
    random_state: int,
) -> tuple[float, float, float | None, int]:
    df = actions_df.reset_index(drop=True)
    if match_id_col in df.columns:
        folds = list(match_kfold(df, n_splits=n_folds, match_id_col=match_id_col, random_state=random_state))
    else:
        from sklearn.model_selection import KFold
        folds = list(KFold(n_splits=n_folds, shuffle=True, random_state=random_state).split(df))
    maes, rmses, spearmans = [], [], []
    for tr_idx, va_idx in folds:
        tr_df, va_df = df.loc[tr_idx], df.loc[va_idx]
        if len(tr_df) < 10:
            continue
        try:
            m = factory()
            m.fit(tr_df, target_col)
            p = m.predict(va_df)
            y = va_df[target_col].astype(float).to_numpy()
            maes.append(float(mean_absolute_error(y, p)))
            rmses.append(float(np.sqrt(mean_squared_error(y, p))))
            corr, _ = spearmanr(y, p)
            if not np.isnan(corr):
                spearmans.append(float(corr))
        except Exception as exc:
            logger.warning("StateValue CV fold failed: %s", exc)
    if not maes:
        return float("inf"), float("inf"), None, 0
    return (
        float(np.mean(maes)), float(np.mean(rmses)),
        float(np.mean(spearmans)) if spearmans else None,
        len(maes),
    )


class StateValueLadder:
    """Trains and ranks all state-value regression model candidates."""

    def __init__(self) -> None:
        self._results: list[StateValueLadderResult] = []

    def run(
        self,
        actions_df: pd.DataFrame,
        target_col: str = "possession_cxg",
        match_id_col: str = "match_id",
        n_folds: int = 5,
        n_estimators: int = 300,
        random_state: int = 42,
    ) -> list[StateValueLadderResult]:
        if actions_df.empty:
            raise ValueError("actions_df is empty")
        if target_col not in actions_df.columns:
            raise ValueError(f"Missing target column: {target_col!r}")

        pos_df = actions_df[actions_df[target_col] > 0].copy()
        ne, rs = n_estimators, random_state

        candidates: list[tuple[str, str, str, Callable, pd.DataFrame]] = [
            ("gamma_glm", "glm", "contextual",
             lambda: GammaStateValueModel(feature_set="contextual", random_state=rs), pos_df),
            ("tweedie_glm", "glm", "contextual",
             lambda: TweedieStateValueModel(feature_set="contextual", random_state=rs), actions_df),
            ("gam_contextual", "gam", "contextual",
             lambda: GAMStateValueModel(feature_set="contextual", random_state=rs), pos_df),
            ("xgb_contextual", "xgboost", "contextual",
             lambda: XGBoostStateValueModel(feature_set="contextual", n_estimators=ne, random_state=rs), actions_df),
            ("lgbm_contextual", "lightgbm", "contextual",
             lambda: LightGBMStateValueModel(feature_set="contextual", n_estimators=ne, random_state=rs), actions_df),
        ]

        results: list[StateValueLadderResult] = []
        for name, family, fset, factory, df_for_fit in candidates:
            logger.info("StateValueLadder: evaluating %s …", name)
            try:
                factory()  # probe availability
            except ImportError as exc:
                logger.warning("StateValueLadder: skipping %s — %s", name, exc)
                continue
            cv_mae, cv_rmse, cv_sp, n_valid = _cv_state_value(
                factory, df_for_fit, target_col, match_id_col, n_folds, random_state
            )
            final = factory()
            final.fit(df_for_fit, target_col)
            results.append(StateValueLadderResult(
                name=name, family=family, feature_set=fset,
                cv_mae=cv_mae, cv_rmse=cv_rmse, cv_spearman=cv_sp,
                n_cv_folds_used=n_valid, model=final,
            ))

        if not results:
            raise RuntimeError("No state-value candidates could be fitted.")
        results.sort(key=lambda r: r.cv_mae)
        for i, r in enumerate(results):
            r.rank = i + 1
        self._results = results
        return results

    def leaderboard(self) -> pd.DataFrame:
        if not self._results:
            raise RuntimeError("No results yet. Call run() first.")
        rows = [{
            "rank": r.rank, "name": r.name, "family": r.family,
            "feature_set": r.feature_set,
            "cv_mae": round(r.cv_mae, 5),
            "cv_rmse": round(r.cv_rmse, 5),
            "cv_spearman": round(r.cv_spearman, 4) if r.cv_spearman is not None else None,
        } for r in self._results]
        return pd.DataFrame(rows).set_index("rank")

    def best(self) -> StateValueLadderResult:
        if not self._results:
            raise RuntimeError("No results yet. Call run() first.")
        return self._results[0]
